version: '3.8'

services:
  bytehost-caller:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FUNCTION_TARGET=callWebsite
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev