name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker compose build

      - name: Test Docker build and API
        run: |
          docker compose up -d
          sleep 10
          # Test the API endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/?url=https://example.com")
          if [ "$response" != "200" ]; then
            echo "API test failed with status code: $response"
            docker compose down
            exit 1
          fi
          echo "API test passed successfully"
          docker compose down

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Functions
        run: |
          gcloud functions deploy callWebsite \
            --gen2 \
            --runtime=nodejs18 \
            --region=australia-southeast1 \
            --source=. \
            --entry-point=callWebsite \
            --trigger-http \
            --allow-unauthenticated